# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Twitter Analysis' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Twitter Analysis
pod 'SwiftyJSON', '~> 4.0'

  target 'Twitter AnalysisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Twitter AnalysisUITests' do
    # Pods for testing
  end

end
